# NOTE: Do not edit, file was generated by jhconvert

Name: python-hulahop
Version: 0.4.8
Release: %mkrel 1
Summary: A pygtk widget for embedding mozilla
License: LGPL
Group: Development/Python
Url: http://sugarlabs.org/

Source: http://dev.laptop.org/pub/sugar/sources/hulahop/hulahop-0.4.8.tar.bz2

Patch: python-hulahop-0.4.8-sugar-hulahop-configure.patch

Requires: pygtk2.0  
Requires: python  
Requires: python-xpcom  

BuildRequires: xulrunner-devel-unstable >= 1.9
BuildRequires: pygtk2.0-devel  
BuildRequires: libgtk+2-devel  
BuildRequires: libpython-devel  
BuildRequires: python-xpcom  

BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)

%description
The hulalop library contains a widget for embedding mozilla.
It's based on pyxpcom and give access to the whole mozilla
xpcom API through python.

%prep
%setup -q -n hulahop-0.4.8
%patch -p1

%build
%configure  \
	--disable-static \
	am_cv_python_pyexecdir=%{python_sitelib}
make 

%install
rm -rf %{buildroot}
make  \
	install \
	DESTDIR=%{buildroot}

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%{_datadir}/*
%{_libdir}/hulahop
%{python_sitelib}/*
%doc COPYING NEWS

