# NOTE: Do not edit, file was generated by jhconvert

Name: python-hulahop
Version: 0.5.0
Release: %mkrel 1
Summary: A pygtk widget for embedding mozilla
License: LGPL
Group: Development/Python
Url: http://sugarlabs.org/

Source: http://download.sugarlabs.org/sources/sucrose/glucose/hulahop/hulahop-0.5.0.tar.bz2

Requires: python-gobject  
Requires: pygtk2.0  
Requires: python  
Requires: python-xpcom  

BuildRequires: autoconf  
BuildRequires: automake  
BuildRequires: gtk+2-devel  
BuildRequires: libtool  
BuildRequires: python-gobject-devel  
BuildRequires: pygtk2.0-devel  
BuildRequires: libpython-devel  
BuildRequires: python-xpcom  
BuildRequires: xulrunner-devel-unstable >= 1.9

BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)


%description
The hulalop library contains a widget for embedding mozilla.
It's based on pyxpcom and give access to the whole mozilla
xpcom API through python.

%prep
%setup -q -n hulahop-0.5.0
echo 'pref(\"general.useragent.vendor\", \"Sugar Labs\");' >> data/prefs.js
echo 'pref(\"general.useragent.vendorSub\", \"#{@release_name}\");' >> data/prefs.js
echo 'pref(\"general.useragent.vendorComment\", \"hulahop/#{version}\");' >> data/prefs.js

%build
%define __libtoolize true
%configure --disable-static am_cv_python_pyexecdir=%{python_sitelib}
make

%install
rm -rf %{buildroot}
make DESTDIR=%{buildroot} install


%clean
rm -rf %{buildroot}

%files 
%defattr(-,root,root,-)
%{_datadir}/*
%{_libdir}/hulahop
%{python_sitelib}/*
%doc COPYING NEWS

