# NOTE: Do not edit, file was generated by jhconvert

Name: python-hulahop
Version: 0.4.9
Release: %mkrel 2
Summary: A pygtk widget for embedding mozilla
License: LGPL
Group: Development/Python
Url: http://sugarlabs.org/

Source: http://download.sugarlabs.org/sources/sucrose/glucose/hulahop/hulahop-0.4.9.tar.bz2

Patch: python-hulahop-0.4.9-sugar-hulahop-configure.patch

Requires: python-gobject  
Requires: pygtk2.0  
Requires: python  
Requires: python-xpcom  

BuildRequires: gtk+2-devel  
BuildRequires: python-gobject-devel  
BuildRequires: pygtk2.0-devel  
BuildRequires: libpython-devel  
BuildRequires: python-xpcom  
BuildRequires: xulrunner-devel-unstable >= 1.9

BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)


%description
The hulalop library contains a widget for embedding mozilla.
It's based on pyxpcom and give access to the whole mozilla
xpcom API through python.

%prep
%setup -q -n hulahop-0.4.9
%patch -p1

%build
echo 'pref("general.useragent.vendor", "Sugar Labs");' >> data/prefs.js
echo 'pref("general.useragent.vendorSub", "0.84");' >> data/prefs.js
echo 'pref("general.useragent.vendorComment", "hulahop/0.4.9");' >> data/prefs.js
libtoolize --copy --force
autoreconf -ivf
%configure --disable-static
make

%install
rm -rf %{buildroot}
make DESTDIR=%{buildroot} install


%clean
rm -rf %{buildroot}

%files 
%defattr(-,root,root,-)
%{_datadir}/*
%{_libdir}/hulahop
%{python_sitelib}/*
%doc COPYING NEWS

